[[servers]]
  Address = "tcp://127.0.0.1:7002"
  Public = "WbCNKwIlPNEqHJN2CsjN/K8IvDy+i3NwwmHFoImZ+yo="
  Description = "Conode_1"
[[servers]]
  Address = "tcp://127.0.0.1:7004"
  Public = "KjeMi9geC1KcX9mM4Fu0TXzlqNm3y/lDsQI3CTgI21Q="
  Description = "Conode_2"
[[servers]]
  Address = "tcp://127.0.0.1:7006"
  Public = "fdya/9Zna14/9wdCJIIZq4kUv6dDl3pxsL0n4mWeugU="
  Description = "Conode_3"
