[[servers]]
  Address = "tcp://127.0.0.1:7002"
  Public = "bZZwk2sjwNxyoAKatidj8y2ePToQMVRBXSesjp3MWng="
  Description = "Conode_1"
[[servers]]
  Address = "tcp://127.0.0.1:7004"
  Public = "UvNnhniDTzgVs/Cw+R8xE8d3VwZG+8B3wG1K1BvmNGY="
  Description = "Conode_2"
[[servers]]
  Address = "tcp://127.0.0.1:7006"
  Public = "gJFBkr9gsu/FCnAmfrkXcC/Ur4jDdqj/LIVZcV1LWqM="
  Description = "Conode_3"
